### ISSUE TITLE
Polling Mixin

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/active_encode#14]
This module would poll the external service at a configured interval and run callbacks (something like `after_state_update`, `after_completion`, `after_error`).  This polling could update the database if the persistence mixin is included as well.

We could look at how Avalon does polling for inspiration: https://github.com/avalonmediasystem/avalon/blob/master/app/jobs/active_encode_job.rb

### Tasks
- [x] Write polling job
- [x] Write module
- [x] Add callbacks to module
- [x] Write tests
- [ ] Update README with how to configure polling and when/how to use mixin

child of https://github.com/samvera-labs/avalon-bundle/issues/176

**Comment by cjcolvar** [comment]
I think the mixin might look like this (pseudocode):
```
  def create
      super
      PollingJob.perform_later(self.id, self.class.name, wait: polling_wait_time)
      self
   end

  define_callbacks :status_update
  define_callbacks :error
  define_callbacks :complete
```

Then the job would be something like:
```
  def perform(id, encoder_class_name)
      job = encoder_class_name.constantize.find(id)
      job.run_callbacks(:status_update)
      case job.status
      when :error
         job.run_callbacks(:error)
      when :complete
        job.run_callbacks(:complete)
      else
        PollingJob.perform_later(id, encoder_class_name, wait: polling_wait_time)
      end
  end
```

**Comment by cjcolvar** [comment]
As @yingfeng-iu pointed out to me, we'll need to override `#cancel` as well to cancel any queued or running polling jobs.  Or maybe we could just handle it as another case in the case statement?
